### ISSUE TITLE
Difficult to find nodes with label and attributes greater than certain values

### ISSUE THREAD

**Issue by ckgagan** [maxdemarzi/neography#184]
Hi I have collection of nodes with different labels and has a attribute :trust. Is there a way to find only those nodes that has trust greater than lets suppose 100?

I went through all the wiki links and found just for equality.
@neo.find_nodes_labeled("Actor", {:name => "Tom Hanks"})

Is there a way to do like "Find all Actor hubs whose trust is greater than 100"?

**Comment by maxdemarzi** [comment]
I'm like 8 months late here, but the answer is to use a cypher query as you might have figured out by now.
