### ISSUE TITLE
loosen excon version requirement?

### ISSUE THREAD

**Issue by jjb** [maxdemarzi/neography#187]
the excon version requirement (~> 0.33.0) results in me being unable to upgrade neography, because my gemfile has a newer version.

Looks like all the changes since .33 have been bugfixes or enhancements, no api changes: https://github.com/excon/excon/blob/master/changelog.txt

(although they don't seem to be using strictly semantic versioning, sadly)

**Comment by maxdemarzi** [comment]
This has been fixed.
