### ISSUE TITLE
Broken pipe (Errno::EPIPE)

### ISSUE THREAD

**Issue by seenickcode** [maxdemarzi/neography#192]
Hello,

I'm using Neography in production with Neo4j 2.1.3 Enterprise.  It's hosted on my VPS running on the same instance as a Sinatra app I have using the Neography gem.

I've been running it for some weeks now and I'm occasionally getting the following error
````
Broken pipe (Errno::EPIPE)
````
This occurs when I run a cypher query, typically to fetch a single node by ID but very occasionally when I run other types of queries.  The typical query it fails for is something like ``MATCH (u:User) WHERE id(u)=<id> RETURN u``

I'm running Neography with the following settings:
````
Neography.configure do |config|
    config.protocol           = "http://"
    config.server             = "localhost"
    config.port               = 7474
    config.directory          = ""  # prefix this path with '/'
    config.cypher_path        = "/cypher"
    config.log_file           = "log/neography.log"
    config.log_enabled        = false
    config.slow_log_threshold = 0    # time in ms for query logging
    config.max_threads        = 20
    config.authentication     = nil  # 'basic' or 'digest'
    config.username           = nil
    config.password           = nil
    config.parser             = MultiJsonParser
    config.http_send_timeout    = 30000
    config.http_receive_timeout = 30000 # 30 seconds
end
````

I'm also running Neo4j with it's default settings.

Any ideas as to why this is happening?

Thanks in advance,
Nick

**Comment by maxdemarzi** [comment]
Not sure what to say here... this is mostly an external issue (network problems) rather than something I can do with neography...

**Comment by seenickcode** [comment]
Yes, correct. The issue turned out to be GC problems with Neo4j memory
settings not configured properly.

Thanks,
