### ISSUE TITLE
Neography should handle clients that have closed explicitly, or not use persistent connections

### ISSUE THREAD

**Issue by sebbacon** [maxdemarzi/neography#193]
The embedded Jetty in neo4j has an idle connection timeout of 30 seconds.

The default configuration parameter for neography that is passed to Excon is to use persistent connections. Excon expects to be able to write to a persistent socket, but this is not always the case.

Neography should either default to passing `:persistent => false` to the Excon connection constructor, or it should catch IO exceptions relating to closed connections (broken pipe when writing, EOF when reading) and create a new connection if necessary.

**Comment by delmendo** [comment]
They should close this. The configure block lets you set persistent to false
