### ISSUE TITLE
Rake Tasks with Java 1.8

### ISSUE THREAD

**Issue by abdalafer** [maxdemarzi/neography#198]
When performing Rake tasks such as:
rake neo4j:start
rake neo4j:reset_yes_i_am_sure
etc...

The rake is executed successfully(neo starts, resets, etc..) but an error message is returned:
'Unable to find any JVMs matching version "1.7"'

It does not appear to be affecting the end result of the rake task so perhaps it is specifically warning or checking java 1.7 and does not know about 1.8 even though the rake works.

my java -version:
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

**Comment by maxdemarzi** [comment]
Current Neo4j expects 1.7, there shouldn't be any issues running on 1.8, but 1.7 is what it is tested against.
