### ISSUE TITLE
Ruby gem contains erroneous references

### ISSUE THREAD

**Issue by aaronhelton** [maxdemarzi/neography#209]
I don't see this already reported, so I am submitting it.

The ruby gem available at https://rubygems.org/gems/neography differs from the GitHub code in at least one respect. In the file neography-1.7.0/lib/neography/rest.rb, there are requires and references that don't exist in the tree:

Line 4: require 'neography/rest/auth'
Line 35: include Auth

https://github.com/maxdemarzi/neography/blob/v1.7.0/lib/neography/rest.rb does not make use of these.

The result for applications relying on the gem directly is:

aaronhelton$ rackup
/Users/aaronhelton/.rvm/gems/ruby-2.2.0/gems/neography-1.7.0/lib/neography/rest.rb:4:in `require': cannot load such file -- neography/rest/auth (LoadError)
	from /Users/aaronhelton/.rvm/gems/ruby-2.2.0/gems/neography-1.7.0/lib/neography/rest.rb:4:in `<top (required)>'
	from /Users/aaronhelton/.rvm/gems/ruby-2.2.0/gems/neography-1.7.0/lib/neography.rb:16:in `require'
	from /Users/aaronhelton/.rvm/gems/ruby-2.2.0/gems/neography-1.7.0/lib/neography.rb:16:in `<top (required)>'
...

The fix appears to be to remove or comment out the offending lines, but I don't know what the larger implications are.

**Comment by ariieh** [comment]
Just came across this also.
``lib/neography/rest.rb:4:in `require': cannot load such file -- neography/rest/auth (LoadError)``

**Comment by maxdemarzi** [comment]
Try 1.7.1, something got screwed up when I pushed the gem.

**Comment by posgarou** [comment]
I'm still running into the problem with 1.7.1.

```
bundle exec rackup
LoadError: no such file to load -- neography/rest/auth
                            require at org/jruby/RubyKernel.java:1071
                             (root) at /Users//.rvm/gems/jruby-1.7.19@rm-portfolio/gems/neography-1.7.1/lib/neography/rest.rb:4
```

Worked when I dropped down to 1.6.0.

**Comment by maxdemarzi** [comment]
I should really stop coding late at night, too many silly mistakes... please try 1.7.2

**Comment by aaronhelton** [comment]
It looks good now.

**Comment by maxdemarzi** [comment]
Great, thanks.
