### ISSUE TITLE
maintaining compatability with Neo4j?

### ISSUE THREAD

**Issue by angelacode** [maxdemarzi/neography#215]
Hi, I am evaluating what to build our app on when using graphene and want to understand the current maintenance and adoption of neography.  

Can you share the current plans for maintenance and compatibility as neo4j continues to evolve?

**Comment by maxdemarzi** [comment]
There are no plans to evolve.  Neography is just a light weight wrapper to the Neo4j REST API. Neo4j 3.x is now using Bolt. The driver you want is https://github.com/neo4jrb/neo4j if you want to build middleware. I tend to build APIs right into Neo4j, so I don't really need a driver anymore. See the series on https://maxdemarzi.com/2017/03/30/building-a-twitter-clone-with-neo4j-part-one/
