### ISSUE TITLE
how do I create a query of neo4j using the neography ruby gem?

### ISSUE THREAD

**Issue by angelacode** [maxdemarzi/neography#220]
http://stackoverflow.com/questions/43822974/how-do-i-create-a-query-of-neo4j-using-the-neography-ruby-gem

**Comment by rdvdijk** [comment]
I've posted an answer to your question on StackOverflow.

**Comment by maxdemarzi** [comment]
@angelacode the problem is the REST API is all but abandoned by Neo4j. They are not really maintaining it. You pretty much have to use Cypher for everything nowadays.  Catch me on skype ( maxdemarzi ) and let's talk about what you are building and let's see how we can help you.
