### ISSUE TITLE
what is the query format for the Phase 2 Nodes?

### ISSUE THREAD

**Issue by angelacode** [maxdemarzi/neography#221]
https://github.com/maxdemarzi/neography/wiki/Phase-2-Nodes

`Neography::Node.find(index, query) `

is query a Lucene query or cypher query?

**Comment by maxdemarzi** [comment]
It is a query for the legacy indexes. It can be a simple value or a complex lucene syntax query.  See:
https://github.com/maxdemarzi/neography/blob/afb3a4724e67d6665d79ca280bb709e69814e893/spec/integration/index_spec.rb#L28 and https://github.com/maxdemarzi/neography/blob/afb3a4724e67d6665d79ca280bb709e69814e893/lib/neography/rest/node_indexes.rb#L51

However this does not use Labels or Schema indexes. For those see https://github.com/maxdemarzi/neography/blob/afb3a4724e67d6665d79ca280bb709e69814e893/spec/integration/rest_labels_spec.rb#L109
