### ISSUE TITLE
how do I pass a string for the relationship in a query?

### ISSUE THREAD

**Issue by angelacode** [maxdemarzi/neography#222]
> Neography::SyntaxException: Parameter maps cannot be used in MATCH patterns (use a literal map instead, eg. "{id: {param}.id}") (line 1, column 21 (offset: 20))
> "MATCH   (fromNode)-[{relationship}]->(toNode) "

My match statement has an error, even though I pass the value to the relationship string:

> query_response = @neo.execute_query("MATCH   (fromNode)-[{relationship}]->(toNode) 
>                                             WHERE   fromNode.bot_client_id = {bot_client_id} AND toNode.epoch_utc_i > {fromTime} AND toNode.epoch_utc_i < {toTime} 
>                                                     
>                                             RETURN  toNode.value
>                                             LIMIT   {limit}", 
>                                             {
>                                                 :fromTime => fromTime, :toTime => toTime, :bot_client_id => @bot_client_id, 
>                                                 :limit => limit, :relationship => relationship.to_sym
>                                             }
>                                         )

**Comment by maxdemarzi** [comment]
```
@neo.execute_query("MATCH (fromNode)-[:" +relationship + "]->(toNode)
WHERE fromNode.bot_client_id = {bot_client_id} AND toNode.epoch_utc_i > {fromTime} AND toNode.epoch_utc_i < {toTime}"
```

**Comment by maxdemarzi** [comment]
You can't use a parameter for a relationship type.
